-- Auto-generated by create-database.sh on 2026-08-04T05:31:49Z
-- Do not edit directly -- edit the source .sql files in inventory/ and re-run this script.
-- Source order: setup_database.sql, then migration_*.sql (alphabetical)

-- ==== setup_database.sql ====
-- MPWT Full Database Setup (Phase 1 + Phase 2)
-- Run with:  sudo -u postgres psql -d mpwt -f setup_database.sql

-- ─────────────────────────────────────────────────────────────────────────────
-- PHASE 1: Base Schema
-- ─────────────────────────────────────────────────────────────────────────────

-- ─────────────────────────────────────────
-- EMPLOYEES
-- ─────────────────────────────────────────
CREATE TABLE employees (
    id              SERIAL PRIMARY KEY,
    employee_id     TEXT    NOT NULL UNIQUE,
    full_name       TEXT    NOT NULL,
    department      TEXT    NOT NULL,
    email           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────
-- SITES  (managed list of internal sites)
-- ─────────────────────────────────────────
CREATE TABLE sites (
    id          SERIAL PRIMARY KEY,
    hostname    TEXT    NOT NULL UNIQUE,
    description TEXT,
    active      BOOLEAN NOT NULL DEFAULT TRUE
);

-- ─────────────────────────────────────────
-- DEVICES
-- ─────────────────────────────────────────
CREATE TABLE devices (
    id              SERIAL PRIMARY KEY,
    employee_id     TEXT    NOT NULL REFERENCES employees(employee_id) ON DELETE CASCADE,
    device_name     TEXT    UNIQUE,
    os_type         TEXT,
    cert_serial     TEXT    UNIQUE,
    cert_status     TEXT    NOT NULL DEFAULT 'PENDING',
    enroll_token    TEXT    UNIQUE,
    token_status    TEXT    NOT NULL DEFAULT 'UNUSED',
    token_expires   TIMESTAMPTZ,
    enrolled_at     TIMESTAMPTZ,
    revoked_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_devices_employee_id ON devices(employee_id);
CREATE INDEX idx_devices_cert_serial  ON devices(cert_serial);
CREATE INDEX idx_devices_enroll_token ON devices(enroll_token);

-- ─────────────────────────────────────────
-- DEVICE ACCESS  (device → site mapping)
-- ─────────────────────────────────────────
CREATE TABLE device_access (
    id          SERIAL PRIMARY KEY,
    device_id   INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    site_id     INTEGER NOT NULL REFERENCES sites(id)   ON DELETE CASCADE,
    granted_by  TEXT,
    granted_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(device_id, site_id)
);

CREATE INDEX idx_device_access_device ON device_access(device_id);
CREATE INDEX idx_device_access_site   ON device_access(site_id);

-- ─────────────────────────────────────────
-- AUDIT LOG
-- ─────────────────────────────────────────
CREATE TABLE audit_log (
    id          SERIAL PRIMARY KEY,
    event       TEXT    NOT NULL,
    employee_id TEXT,
    device_id   INTEGER,
    device_name TEXT,
    detail      TEXT,
    ip_address  TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─────────────────────────────────────────
-- AUTO-UPDATE updated_at
-- ─────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER employees_updated_at
    BEFORE UPDATE ON employees
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TRIGGER devices_updated_at
    BEFORE UPDATE ON devices
    FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- ─────────────────────────────────────────────────────────────────────────────
-- PHASE 2: Server-Verified Policy Binding & Anomaly Detection
-- ─────────────────────────────────────────────────────────────────────────────

-- ─────────────────────────────────────────
-- Indexes on audit_log for anomaly queries
-- ─────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_audit_event
    ON audit_log(event);

CREATE INDEX IF NOT EXISTS idx_audit_device_id
    ON audit_log(device_id);

CREATE INDEX IF NOT EXISTS idx_audit_employee_id
    ON audit_log(employee_id);

-- ─────────────────────────────────────────
-- VIEW: anomaly events for IT admin review
-- ─────────────────────────────────────────
CREATE OR REPLACE VIEW v_anomalies AS
SELECT
    al.created_at,
    al.event,
    al.employee_id,
    al.device_id,
    al.device_name      AS enrolled_device_name,
    al.detail,
    al.ip_address
FROM audit_log al
WHERE al.event IN (
    'ANOMALY_HOSTNAME_MISMATCH',
    'CN_MISMATCH',
    'HMAC_FAIL'
)
ORDER BY al.created_at DESC;

-- ─────────────────────────────────────────
-- VIEW: enrollment summary per employee
-- ─────────────────────────────────────────
CREATE OR REPLACE VIEW v_enrollment_summary AS
SELECT
    e.employee_id,
    e.full_name,
    e.department,
    d.id            AS device_id,
    d.device_name,
    d.os_type,
    d.cert_status,
    d.cert_serial,
    d.enrolled_at,
    d.revoked_at,
    (
        SELECT string_agg(s.hostname, ', ' ORDER BY s.hostname)
        FROM   device_access da
        JOIN   sites s ON s.id = da.site_id
        WHERE  da.device_id = d.id
    )               AS allowed_sites
FROM employees e
JOIN devices   d ON d.employee_id = e.employee_id
ORDER BY e.employee_id, d.id;

-- Done.
SELECT 'Database setup complete (Phase 1 + Phase 2).' AS status;

-- ==== migration_add_tpm_columns.sql ====
-- Migration: add TPM attestation tracking to devices table
-- Run against the mpwt database before deploying the updated enroll.py

ALTER TABLE devices ADD COLUMN IF NOT EXISTS tpm_verified  BOOLEAN DEFAULT FALSE;
ALTER TABLE devices ADD COLUMN IF NOT EXISTS tpm_ek_serial TEXT;

-- Optional but recommended: index for auditing/reporting TPM coverage
CREATE INDEX IF NOT EXISTS idx_devices_tpm_verified ON devices (tpm_verified);

-- ==== migration_drop_device_name_unique.sql ====
-- Migration: remove uniqueness constraint on devices.device_name

ALTER TABLE devices DROP CONSTRAINT IF EXISTS devices_device_name_key;
