"""
services/policy_service.py  -  Server-Verified Policy Binding
==============================================================
"""

import hashlib
import hmac
import os
import re
import subprocess
import tempfile
import logging

logger = logging.getLogger(__name__)

# ── HMAC key ──────────────────────────────────────────────────────────────────
_HMAC_KEY_ENV   = "MPWT_POLICY_HMAC_KEY"
_HMAC_OU_PREFIX = "MPWT-TOKEN-"
_HMAC_HEX_LEN   = 32

def _read_credential(name: str) -> str | None:
    cred_dir = os.environ.get("CREDENTIALS_DIRECTORY")
    if not cred_dir:
        return None
    path = os.path.join(cred_dir, name)
    if not os.path.isfile(path):
        return None
    with open(path, "r") as f:
        return f.read().strip()


def _hmac_key() -> bytes:
    key = _read_credential("policy_hmac_key") or os.environ.get(_HMAC_KEY_ENV, "")
    if not key:
        raise RuntimeError(
            f"{_HMAC_KEY_ENV} is not set. "
            'Generate: python3 -c "import secrets; print(secrets.token_hex(32))"'
        )
    return key.encode("utf-8")


def _make_hmac(token: str, employee_id: str, cn: str, os_type: str) -> str:
    message = f"{token}|{employee_id}|{cn}|{os_type}".encode("utf-8")
    full = hmac.new(_hmac_key(), message, hashlib.sha256).hexdigest()
    return full[:_HMAC_HEX_LEN]


def _make_hmac_ou(token: str, employee_id: str, cn: str, os_type: str) -> str:
    return f"{_HMAC_OU_PREFIX}{_make_hmac(token, employee_id, cn, os_type)}"


# ── Config / script generation ────────────────────────────────────────────────

def generate_config_file(
    token:        str,
    employee_id:  str,
    cn:           str,
    os_type:      str,
    device_order: int,
) -> tuple[str, str]:
    """Return (file_content, filename) for the given OS."""
    hmac_ou = _make_hmac_ou(token, employee_id, cn, os_type)
    suffix  = f"{employee_id}-D{device_order}"

    if os_type == "windows":
        return _windows_ps1(cn, hmac_ou, suffix), f"mpwt-enroll-{suffix}.ps1"
    elif os_type == "macos":
        return _macos_sh(cn, hmac_ou, suffix), f"mpwt-enroll-{suffix}.sh"
    else:
        return _linux_sh(cn, hmac_ou, suffix), f"mpwt-enroll-{suffix}.sh"

def _windows_ps1(cn: str, hmac_ou: str, suffix: str) -> str:
    """
    Self-contained PowerShell enrollment script -- GUI-only, no visible console.

    - On first launch (double-click / right-click -> Run with PowerShell) the
      script immediately relaunches itself as a hidden background process
      (-WindowStyle Hidden) and the original visible console exits right
      away. Everything the user sees afterwards is the WinForms window --
      there is no console output at all, so every status/progress line that
      used to be Write-Host now goes into an in-window log textbox instead.
    - Custom WinForms window (not the native FolderBrowserDialog tree view)
      for the CSR save location, with a "Browse..." button that opens the
      native picker only as a secondary, optional step. Larger font
      (Segoe UI 10pt) and DPI-aware scaling so text isn't cramped/blurry on
      scaled displays.
    - Always attempts the TPM-backed CNG provider first, unconditionally.
      Get-Tpm is used only to print a best-effort status line, never to
      decide whether to try TPM: on a non-elevated session it can silently
      report "not present" even when a TPM genuinely exists, since the
      underlying WMI query is admin-gated. If the real TPM attempt fails,
      the script automatically retries once with the legacy CSP so the
      user still ends up with a CSR without any manual intervention.
    - Runs certreq as a separate OS process (Start-Process) with
      stdout/stderr redirected to files at the OS level. This avoids
      PowerShell's native "2>&1" stream merging, which turns ordinary
      stderr chatter from certreq into a red ErrorRecord even when the
      command actually succeeds.
    - At the end, reverts this account's ExecutionPolicy back to Undefined --
      this undoes the one-time "Set-ExecutionPolicy RemoteSigned -Scope
      CurrentUser" step from the setup instructions, so the account is left
      as it was before. NOTE: this means that step must be repeated manually
      before any FUTURE script (e.g. a later re-enrollment) will run via
      right-click -> Run with PowerShell again. That first (briefly visible)
      launch is still what requires the execution policy to allow scripts;
      the hidden relaunch below additionally passes -ExecutionPolicy Bypass
      just for its own child process so it never gets stuck prompting with
      no console to answer on.
    """
    csr_name = f"request-{suffix}.csr"

    return f'''# =============================================================
# MPWT Network Access Enrollment -- Server-Generated Script
# DO NOT EDIT THIS FILE. Any modification will invalidate enrollment.
# MPWT-POLICY-HMAC-OU: {hmac_ou}
# =============================================================

param(
    [switch]$Hidden
)

# ---- Relaunch invisibly on first run (see docstring) -----------------------
if (-not $Hidden) {{
    Start-Process -FilePath "powershell.exe" -ArgumentList @(
        "-NoProfile", "-ExecutionPolicy", "Bypass", "-WindowStyle", "Hidden",
        "-File", "`"$PSCommandPath`"", "-Hidden"
    ) -WindowStyle Hidden
    exit
}}

Add-Type -AssemblyName System.Windows.Forms | Out-Null
Add-Type -AssemblyName System.Drawing | Out-Null
[System.Windows.Forms.Application]::EnableVisualStyles()

$CN         = "{cn}"
$HmacOU     = "{hmac_ou}"
$CsrName    = "{csr_name}"
$Hostname   = $env:COMPUTERNAME
$DefaultDir = [Environment]::GetFolderPath("Desktop")

try {{
    # ---- Build the GUI (this replaces every console Write-Host below) -----
    $AppFont = New-Object System.Drawing.Font("Segoe UI", 10)
    $LogFont = New-Object System.Drawing.Font("Segoe UI", 9)

    $form = New-Object System.Windows.Forms.Form
    $form.Text            = "MPWT Enrollment"
    $form.Font            = $AppFont
    $form.AutoScaleMode   = [System.Windows.Forms.AutoScaleMode]::Dpi
    $form.Size            = New-Object System.Drawing.Size(520, 430)
    $form.StartPosition   = "CenterScreen"
    $form.FormBorderStyle = "FixedDialog"
    $form.MaximizeBox     = $false
    $form.MinimizeBox     = $false
    $form.TopMost         = $true

    $lblInstruction = New-Object System.Windows.Forms.Label
    $lblInstruction.Text     = "Choose where to save the certificate request (CSR):"
    $lblInstruction.AutoSize = $true
    $lblInstruction.Location = New-Object System.Drawing.Point(20, 20)
    $form.Controls.Add($lblInstruction)

    $txtPath = New-Object System.Windows.Forms.TextBox
    $txtPath.Text     = $DefaultDir
    $txtPath.ReadOnly = $true
    $txtPath.Font     = $AppFont
    $txtPath.Location = New-Object System.Drawing.Point(20, 50)
    $txtPath.Size     = New-Object System.Drawing.Size(360, 28)
    $form.Controls.Add($txtPath)

    $btnBrowse = New-Object System.Windows.Forms.Button
    $btnBrowse.Text     = "Browse..."
    $btnBrowse.Font     = $AppFont
    $btnBrowse.Location = New-Object System.Drawing.Point(390, 48)
    $btnBrowse.Size     = New-Object System.Drawing.Size(100, 30)
    $form.Controls.Add($btnBrowse)

    $lblFile = New-Object System.Windows.Forms.Label
    $lblFile.Text      = "File to be created: $CsrName"
    $lblFile.AutoSize  = $true
    $lblFile.ForeColor = [System.Drawing.Color]::DimGray
    $lblFile.Location  = New-Object System.Drawing.Point(20, 90)
    $form.Controls.Add($lblFile)

    $lblLog = New-Object System.Windows.Forms.Label
    $lblLog.Text     = "Status:"
    $lblLog.AutoSize = $true
    $lblLog.Location = New-Object System.Drawing.Point(20, 125)
    $form.Controls.Add($lblLog)

    $txtLog = New-Object System.Windows.Forms.TextBox
    $txtLog.Multiline  = $true
    $txtLog.ReadOnly   = $true
    $txtLog.ScrollBars = "Vertical"
    $txtLog.Font       = $LogFont
    $txtLog.Location   = New-Object System.Drawing.Point(20, 150)
    $txtLog.Size       = New-Object System.Drawing.Size(470, 170)
    $form.Controls.Add($txtLog)

    $btnGenerate = New-Object System.Windows.Forms.Button
    $btnGenerate.Text     = "Generate CSR"
    $btnGenerate.Font     = $AppFont
    $btnGenerate.Location = New-Object System.Drawing.Point(270, 335)
    $btnGenerate.Size     = New-Object System.Drawing.Size(120, 34)
    $form.Controls.Add($btnGenerate)

    $btnClose = New-Object System.Windows.Forms.Button
    $btnClose.Text     = "Cancel"
    $btnClose.Font     = $AppFont
    $btnClose.Location = New-Object System.Drawing.Point(400, 335)
    $btnClose.Size     = New-Object System.Drawing.Size(90, 34)
    $form.Controls.Add($btnClose)

    function Add-Log([string]$Text) {{
        $txtLog.AppendText("$Text`r`n")
    }}

    $btnBrowse.Add_Click({{
        $FolderDialog = New-Object System.Windows.Forms.FolderBrowserDialog
        $FolderDialog.Description        = "Select a folder to save the CSR"
        $FolderDialog.SelectedPath       = $txtPath.Text
        $FolderDialog.ShowNewFolderButton = $true
        if ($FolderDialog.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK -and $FolderDialog.SelectedPath) {{
            $txtPath.Text = $FolderDialog.SelectedPath
        }}
    }})

    $btnClose.Add_Click({{ $form.Close() }})

    $btnGenerate.Add_Click({{
        $btnGenerate.Enabled = $false
        $btnBrowse.Enabled   = $false

        Add-Log "=== MPWT Enrollment - CSR Generation ==="
        Add-Log "Employee/Device suffix: {suffix}"

        # ---- TPM status (informational only -- see docstring) -------------
        try {{
            $tpm = Get-Tpm
            Add-Log "TPM status (best-effort): Present=$($tpm.TpmPresent) Ready=$($tpm.TpmReady)"
        }} catch {{
            Add-Log "Could not query TPM status (non-fatal) -- will still attempt hardware-backed key first."
        }}

        $SaveDir = $txtPath.Text
        if (-not $SaveDir) {{ $SaveDir = $DefaultDir }}
        if (-not (Test-Path $SaveDir)) {{
            New-Item -ItemType Directory -Path $SaveDir -Force | Out-Null
        }}
        $CsrPath = Join-Path $SaveDir $CsrName
        Add-Log "Save location: $CsrPath"

        # ---- Ordered list of provider attempts -----------------------------
        # TPM-backed CNG is always attempted first -- unconditionally,
        # regardless of what Get-Tpm reported above -- with the legacy CSP
        # as automatic fallback if that attempt doesn't produce a CSR.
        $Attempts = @()
        $Attempts += [PSCustomObject]@{{
            Name              = "TPM (Microsoft Platform Crypto Provider)"
            IsTpm             = $true
            ProviderName      = "Microsoft Platform Crypto Provider"
            KeySpecLine       = ""
            ProviderTypeLine  = ""
        }}
        $Attempts += [PSCustomObject]@{{
            Name              = "Software-protected (Microsoft RSA SChannel Cryptographic Provider)"
            IsTpm             = $false
            ProviderName      = "Microsoft RSA SChannel Cryptographic Provider"
            KeySpecLine       = "KeySpec               = 1"
            ProviderTypeLine  = "ProviderType          = 12"
        }}

        $Subject = "CN=$CN,OU=$Hostname,OU=$HmacOU,O=MPWT,C=KH"

        $CsrCreated = $false
        $UsedTpm    = $false
        $LastExit   = -1
        $LastOutput = ""

        # certreq will interactively prompt "overwrite?" if the target file
        # already exists (e.g. from an earlier attempt/run), but there is no
        # console attached to answer it -- that hang shows up as exit code
        # -2147023673 (ERROR_CANCELLED). Remove any leftover file up front so
        # it never has anything to ask about.
        if (Test-Path $CsrPath) {{
            Remove-Item -Path $CsrPath -Force -ErrorAction SilentlyContinue
        }}

        foreach ($Attempt in $Attempts) {{
            Add-Log "Generating certificate request using: $($Attempt.Name) ..."

            # Same reason as above -- clear it before every attempt, not
            # just once, in case a prior attempt in this same run partially
            # wrote the file before failing.
            if (Test-Path $CsrPath) {{
                Remove-Item -Path $CsrPath -Force -ErrorAction SilentlyContinue
            }}

            $InfContent = @"
[Version]
Signature=`"`$Windows NT`"

[NewRequest]
Subject               = "$Subject"
KeyLength             = 2048
MachineKeySet         = FALSE
SMIME                 = FALSE
PrivateKeyArchive     = FALSE
UserProtected         = FALSE
UseExistingKeySet     = FALSE
ProviderName          = "$($Attempt.ProviderName)"
$($Attempt.KeySpecLine)
$($Attempt.ProviderTypeLine)
RequestType           = PKCS10
HashAlgorithm         = sha256

[EnhancedKeyUsageExtension]
OID = 1.3.6.1.5.5.7.3.2
"@

            $TempInf = Join-Path $env:TEMP "mpwt-enroll-{suffix}-$(Get-Random).inf"
            Set-Content -Path $TempInf -Value $InfContent -Encoding ASCII

            # ---- Run certreq as a separate OS process. Stdout/stderr are
            #      redirected to files at the OS level via Start-Process --
            #      this is real process-level redirection, not PowerShell's
            #      "2>&1" stream merge, so certreq's routine stderr chatter
            #      never gets surfaced as a red ErrorRecord.
            $StdOutFile = [System.IO.Path]::GetTempFileName()
            $StdErrFile = [System.IO.Path]::GetTempFileName()

            $proc = Start-Process -FilePath "certreq.exe" `
                -ArgumentList @("-new", "`"$TempInf`"", "`"$CsrPath`"") `
                -NoNewWindow -Wait -PassThru `
                -RedirectStandardOutput $StdOutFile -RedirectStandardError $StdErrFile

            $LastExit   = $proc.ExitCode
            $LastOutput = ((Get-Content $StdOutFile -Raw -ErrorAction SilentlyContinue) + "`n" +
                           (Get-Content $StdErrFile -Raw -ErrorAction SilentlyContinue))

            Remove-Item -Path $TempInf, $StdOutFile, $StdErrFile -ErrorAction SilentlyContinue

            if ($LastExit -eq 0 -and (Test-Path $CsrPath)) {{
                $CsrCreated = $true
                $UsedTpm    = $Attempt.IsTpm
                break
            }} else {{
                Add-Log "  -> that attempt failed (exit code $LastExit)."
            }}
        }}

        # ---- Report result --------------------------------------------------
        if ($CsrCreated) {{
            Add-Log "CSR created: $CsrPath"
            if ($UsedTpm) {{
                Add-Log "Private key secured in TPM (non-exportable)."
            }} else {{
                Add-Log "Private key secured in Windows key store (non-exportable)."
            }}
            Add-Log ""
            Add-Log "Done. Please send '$CsrName' back to your Admin."
        }} else {{
            Add-Log ""
            Add-Log "certreq FAILED (exit code $LastExit):"
            Add-Log $LastOutput
            Add-Log "CSR generation failed. Contact IT admin."
        }}

        # ---- Revert ExecutionPolicy back to the account's original default -
        try {{
            Set-ExecutionPolicy -ExecutionPolicy Undefined -Scope CurrentUser -Force -ErrorAction Stop
        }} catch {{
            Add-Log "Note: could not reset execution policy automatically ($($_.Exception.Message))."
        }}

        $btnClose.Text    = "Close"
        $btnClose.Enabled = $true
    }})

    [void]$form.ShowDialog()
}}
catch {{
    [System.Windows.Forms.MessageBox]::Show(
        "Unexpected error: $($_.Exception.Message)",
        "MPWT Enrollment - Error",
        [System.Windows.Forms.MessageBoxButtons]::OK,
        [System.Windows.Forms.MessageBoxIcon]::Error
    ) | Out-Null
}}
'''

def _macos_sh(cn: str, hmac_ou: str, suffix: str) -> str:
    """
    Self-contained macOS enrollment script -- shell equivalent of _windows_ps1.

    - Distributed as a plain .sh file, run manually via Terminal
      (`chmod +x` + `./mpwt-enroll-<suffix>.sh`) rather than as a
      double-clicked .command file. This sidesteps the Finder/
      LaunchServices Gatekeeper check entirely -- that check (which
      produces "cannot be opened because it is from an unidentified
      developer", or on some macOS versions/download sources "is damaged
      and can't be opened") only fires on double-click, not on direct
      shell execution. If the file still carries a quarantine flag from
      however it was downloaded (Telegram, browser, etc.), a one-time
      `xattr -d com.apple.quarantine <file>` clears it; the bot's
      instructions below cover this.
    - Hardened compared to the previous .command version:
        * `umask 077` before anything is created, so no file is ever
          briefly group/world-readable.
        * The private key's temp file is pre-created with restrictive
          permissions before openssl writes to it.
        * `trap ... EXIT INT TERM` (not just EXIT), so the temp
          workdir is cleaned up even on Ctrl-C or an unexpected exit.
        * The chosen save folder is validated as an existing, writable
          directory before anything is written there.
        * Required tools (openssl, security, hostname, mktemp,
          osascript) are checked up front with `command -v`, so the
          script fails with a clear message instead of behaving
          unexpectedly if something is missing.
    - Uses AppleScript (osascript) dialogs for the folder picker and
      status messages -- this is the WinForms-window equivalent, since
      there is no first-party way to build a native Cocoa GUI from a
      shell script.
    - Generates the CSR with `openssl req -new`, then immediately
      imports the resulting private key into the login Keychain and
      shreds the on-disk copy (`srm -z`, falling back to `rm` if srm
      isn't available). This is "Keychain-protected", not true Secure
      Enclave hardware backing -- that would require a signed helper
      app, which is out of scope here.
    - Does NOT attempt the Windows script's "relaunch hidden" trick: on
      macOS that fights Terminal.app's "close window with running child
      processes?" prompt, so the Terminal window is left visible and the
      user closes it manually once the final dialog appears.
    """
    csr_name = f"request-{suffix}.csr"
    script_name = f"mpwt-enroll-{suffix}.sh"

    return f'''#!/bin/bash
# =============================================================
# MPWT Network Access Enrollment -- Server-Generated Script (macOS)
# DO NOT EDIT THIS FILE. Any modification will invalidate enrollment.
# MPWT-POLICY-HMAC-OU: {hmac_ou}
#
# HOW TO RUN:
#   chmod +x {script_name} && ./{script_name}
#   (running via Terminal avoids Finder's Gatekeeper double-click check)
#   If macOS still blocks it as quarantined/unsigned, run once first:
#     xattr -d com.apple.quarantine {script_name}
# =============================================================

set -euo pipefail
IFS=$'\\n\\t'
umask 077

CN="{cn}"
HMAC_OU="{hmac_ou}"
SUFFIX="{suffix}"
CSR_NAME="request-${{SUFFIX}}.csr"

if [ "$(uname -s)" != "Darwin" ]; then
    echo "This script is for macOS only." >&2
    exit 1
fi
for tool in openssl security hostname mktemp osascript; do
    command -v "$tool" >/dev/null 2>&1 || {{ echo "Missing required tool: $tool" >&2; exit 1; }}
done

HOSTNAME_SHORT="$(hostname -s)"
DEFAULT_DIR="$HOME/Downloads"

SAVE_DIR=$(osascript <<APPLESCRIPT
set defaultDir to POSIX file "$DEFAULT_DIR"
try
    set chosenFolder to choose folder with prompt "Choose where to save the certificate request (CSR):" default location defaultDir
    return POSIX path of chosenFolder
on error
    return ""
end try
APPLESCRIPT
)

if [ -z "$SAVE_DIR" ]; then
    osascript -e 'display dialog "Cancelled. No folder selected." buttons {{"OK"}} with icon caution'
    exit 1
fi

SAVE_DIR="${{SAVE_DIR%/}}"

if [ ! -d "$SAVE_DIR" ] || [ ! -w "$SAVE_DIR" ]; then
    osascript -e "display dialog \\"Selected folder is not writable: $SAVE_DIR\\" buttons {{\\"OK\\"}} with icon stop"
    exit 1
fi
CSR_PATH="$SAVE_DIR/$CSR_NAME"

CONFIRM=$(osascript <<APPLESCRIPT
display dialog "File to be created:" & return & "$CSR_NAME" & return & return & "Save location:" & return & "$SAVE_DIR" buttons {{"Cancel", "Generate CSR"}} default button "Generate CSR" with icon note
APPLESCRIPT
)

if [[ "$CONFIRM" != *"Generate CSR"* ]]; then
    exit 0
fi

WORKDIR=$(mktemp -d)
chmod 700 "$WORKDIR"
trap 'rm -rf "$WORKDIR"' EXIT INT TERM

CNF_PATH="$WORKDIR/mpwt-enroll-${{SUFFIX}}.cnf"
KEY_TMP="$WORKDIR/client-${{SUFFIX}}.key"
( umask 077; : > "$KEY_TMP" )

cat > "$CNF_PATH" <<CNFEOF
[ req ]
default_bits        = 2048
prompt              = no
default_md          = sha256
req_extensions      = v3_req
distinguished_name  = dn

[ dn ]
CN = $CN
0.OU = $HOSTNAME_SHORT
1.OU = $HMAC_OU
O    = MPWT
C    = KH

[ v3_req ]
basicConstraints = CA:FALSE
keyUsage         = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = clientAuth
CNFEOF
chmod 600 "$CNF_PATH"

osascript -e 'display notification "Generating key and certificate request..." with title "MPWT Enrollment"'

rm -f "$CSR_PATH"

STDOUT_FILE="$WORKDIR/openssl.out"
STDERR_FILE="$WORKDIR/openssl.err"

OPENSSL_OK=1
/usr/bin/openssl req -new -newkey rsa:2048 -nodes \\
    -config "$CNF_PATH" \\
    -keyout "$KEY_TMP" \\
    -out "$CSR_PATH" \\
    >"$STDOUT_FILE" 2>"$STDERR_FILE" || OPENSSL_OK=0

if [ "$OPENSSL_OK" -ne 1 ] || [ ! -f "$CSR_PATH" ]; then
    ERR_MSG=$(tail -20 "$STDOUT_FILE" "$STDERR_FILE" 2>/dev/null)
    osascript -e "display dialog \\"CSR generation FAILED.\\n\\n$ERR_MSG\\n\\nContact IT admin.\\" buttons {{\\"OK\\"}} with icon stop"
    exit 1
fi
chmod 644 "$CSR_PATH"

KEYCHAIN_IMPORT_OK=1
/usr/bin/security import "$KEY_TMP" -k "$HOME/Library/Keychains/login.keychain-db" \\
    -T /usr/bin/openssl -x >/dev/null 2>"$WORKDIR/import.err" || KEYCHAIN_IMPORT_OK=0

if command -v srm >/dev/null 2>&1; then
    srm -z "$KEY_TMP" 2>/dev/null || rm -f "$KEY_TMP"
else
    rm -f "$KEY_TMP"
fi

if [ "$KEYCHAIN_IMPORT_OK" -eq 1 ]; then
    KEY_STATUS="Private key imported into macOS Keychain; plaintext copy shredded."
else
    IMPORT_ERR=$(tail -3 "$WORKDIR/import.err" 2>/dev/null)
    KEY_STATUS="Note: could not import key into Keychain automatically ($IMPORT_ERR). Plaintext key was still shredded. CSR was created successfully."
fi

osascript -e "display dialog \\"CSR created:\\n$CSR_PATH\\n\\n$KEY_STATUS\\n\\nDone. Please send '$CSR_NAME' back to your Admin.\\n\\nYou can close this Terminal window now.\\" buttons {{\\"OK\\"}} default button \\"OK\\" with icon note"

exit 0
'''

def _linux_sh(cn: str, hmac_ou: str, suffix: str) -> str:
    """
    Self-contained Linux enrollment script -- TPM-first key protection.

    Key handling order (mirrors the Windows script's TPM-first-then-CSP
    approach):
      1. TPM2, via tpm2-tss-engine (`tpm2tss-genkey` + OpenSSL "tpm2tss"
         engine). The RSA key is generated *inside* the TPM and never
         exists in plaintext on disk or in memory outside the TPM -- the
         file written to disk (`client-<suffix>.tpm.key`) is just a wrapped
         key handle, useless without that specific TPM. This is the actual
         non-exportable path and is attempted unconditionally whenever
         tpm2tss-genkey + a TPM device node are present, same as the
         Windows script always tries Get-Tpm's provider first regardless
         of what Get-Tpm itself reports.
      2. Software-protected fallback: only used if step 1's tools/device
         aren't present or the TPM attempt fails. Key is generated in
         plaintext in a private temp dir, immediately imported into the
         freedesktop Secret Service (GNOME Keyring / KWallet) via
         `secret-tool`, and the plaintext copy is shredded. This key CAN
         technically be exported by anyone with access to the keyring
         while unlocked -- it is software-protected, not hardware-backed --
         but it never touches disk as a bare file.
      3. There is NO third fallback that writes a plaintext .key file next
         to the CSR. If both step 1 and step 2 fail, CSR generation fails
         outright and the user is told to contact IT -- silently handing
         them an unprotected private key file is worse than failing loudly.
    """
    csr_name = f"request-{suffix}.csr"
    script_name = f"mpwt-enroll-{suffix}.sh"

    return f'''#!/bin/bash
# =============================================================
# MPWT Network Access Enrollment -- Server-Generated Script (Linux)
# DO NOT EDIT THIS FILE. Any modification will invalidate enrollment.
# MPWT-POLICY-HMAC-OU: {hmac_ou}
#
# HOW TO RUN:
#   chmod +x {script_name} && ./{script_name}
#
# For TPM-backed (non-exportable) keys, install first:
#   Debian/Ubuntu: sudo apt install tpm2-tss-engine tpm2-tools
#   Fedora/RHEL:   sudo dnf install tpm2-tss-engine tpm2-tools
# If these aren't installed, the script still works but falls back to a
# software-protected key stored in your keyring instead of the TPM.
# =============================================================

set -euo pipefail
IFS=$'\\n\\t'
umask 077

CN="{cn}"
HMAC_OU="{hmac_ou}"
SUFFIX="{suffix}"
CSR_NAME="request-${{SUFFIX}}.csr"

if [ "$(uname -s)" != "Linux" ]; then
    echo "This script is for Linux only." >&2
    exit 1
fi
for tool in openssl hostname mktemp; do
    command -v "$tool" >/dev/null 2>&1 || {{ echo "Missing required tool: $tool" >&2; exit 1; }}
done

HOSTNAME_SHORT="$(hostname -s 2>/dev/null || hostname)"
DEFAULT_DIR="$HOME/Downloads"
mkdir -p "$DEFAULT_DIR"

# ---- Pick a dialog backend: zenity, then kdialog, then plain terminal -----
UI_BACKEND=""
if command -v zenity >/dev/null 2>&1; then
    UI_BACKEND="zenity"
elif command -v kdialog >/dev/null 2>&1; then
    UI_BACKEND="kdialog"
else
    UI_BACKEND="tty"
fi

ui_choose_folder() {{
    local prompt="$1"
    case "$UI_BACKEND" in
        zenity)  zenity --file-selection --directory --title="$prompt" --filename="$DEFAULT_DIR/" 2>/dev/null || true ;;
        kdialog) kdialog --getexistingdirectory "$DEFAULT_DIR" --title "$prompt" 2>/dev/null || true ;;
        tty)     read -r -p "$prompt [$DEFAULT_DIR]: " ans; echo "${{ans:-$DEFAULT_DIR}}" ;;
    esac
}}

ui_confirm() {{
    local msg="$1"
    case "$UI_BACKEND" in
        zenity)  zenity --question --title="MPWT Enrollment" --text="$msg" 2>/dev/null ;;
        kdialog) kdialog --yesno "$msg" 2>/dev/null ;;
        tty)     read -r -p "$msg [y/N]: " ans; [[ "$ans" =~ ^[Yy]$ ]] ;;
    esac
}}

ui_notify() {{
    local msg="$1"
    case "$UI_BACKEND" in
        zenity)  zenity --notification --text="$msg" 2>/dev/null || true ;;
        kdialog) kdialog --passivepopup "$msg" 5 2>/dev/null || true ;;
        tty)     printf '%b\n' "$msg" ;;
    esac
}}

ui_alert() {{
    local msg="$1"
    case "$UI_BACKEND" in
        zenity)  zenity --info --title="MPWT Enrollment" --text="$msg" 2>/dev/null || true ;;
        kdialog) kdialog --msgbox "$msg" 2>/dev/null || true ;;
        tty)     printf '%b\n' "$msg" ;;
    esac
}}

# ---- Step 1: choose save location ----
SAVE_DIR="$(ui_choose_folder "Choose where to save the certificate request (CSR):")"
if [ -z "$SAVE_DIR" ]; then
    ui_alert "Cancelled. No folder selected."
    exit 1
fi
SAVE_DIR="${{SAVE_DIR%/}}"

if [ ! -d "$SAVE_DIR" ] || [ ! -w "$SAVE_DIR" ]; then
    ui_alert "Selected folder is not writable: $SAVE_DIR"
    exit 1
fi
CSR_PATH="$SAVE_DIR/$CSR_NAME"

# ---- Step 2: confirm ----
if ! ui_confirm "File to be created: ${{CSR_NAME}}\\nSave location: ${{SAVE_DIR}}"; then
    exit 0
fi

# ---- Step 3: private working directory ----
WORKDIR=$(mktemp -d)
chmod 700 "$WORKDIR"
trap 'rm -rf "$WORKDIR"' EXIT INT TERM

CNF_PATH="$WORKDIR/mpwt-enroll-${{SUFFIX}}.cnf"

cat > "$CNF_PATH" <<CNFEOF
[ req ]
default_bits        = 2048
prompt              = no
default_md          = sha256
req_extensions      = v3_req
distinguished_name  = dn

[ dn ]
CN = $CN
0.OU = $HOSTNAME_SHORT
1.OU = $HMAC_OU
O    = MPWT
C    = KH

[ v3_req ]
basicConstraints = CA:FALSE
keyUsage         = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = clientAuth
CNFEOF
chmod 600 "$CNF_PATH"

rm -f "$CSR_PATH"
STDOUT_FILE="$WORKDIR/openssl.out"
STDERR_FILE="$WORKDIR/openssl.err"

ui_notify "Generating certificate request..."

CSR_CREATED=0
USED_TPM=0
KEY_STATUS=""

# ---- Attempt 1: TPM2-backed key (non-exportable) ---------------------------
# The key is created *inside* the TPM by tpm2tss-genkey; the file it writes
# is a wrapped handle, not the raw key, so there is nothing exportable on
# disk. openssl then signs the CSR through the tpm2tss engine, which talks
# to the TPM for the actual signing operation -- the private key material
# itself never leaves the chip.
if command -v tpm2tss-genkey >/dev/null 2>&1 \\
   && {{ [ -e /dev/tpmrm0 ] || [ -e /dev/tpm0 ]; }} \\
   && openssl engine tpm2tss >/dev/null 2>&1; then

    TPM_KEY_PATH="$WORKDIR/client-${{SUFFIX}}.tpm.key"

    if tpm2tss-genkey -a rsa "$TPM_KEY_PATH" >"$WORKDIR/tpmgen.out" 2>"$WORKDIR/tpmgen.err"; then
        if openssl req -engine tpm2tss -keyform engine \\
            -new -key "$TPM_KEY_PATH" \\
            -config "$CNF_PATH" \\
            -out "$CSR_PATH" \\
            >"$STDOUT_FILE" 2>"$STDERR_FILE"; then

            if [ -f "$CSR_PATH" ]; then
                # Keep the wrapped key file -- it is only usable together
                # with this specific TPM, so it is safe to keep next to
                # the CSR. It is NOT a plaintext exportable private key.
                TPM_KEY_KEEP="$SAVE_DIR/client-${{SUFFIX}}.tpm.key"
                cp "$TPM_KEY_PATH" "$TPM_KEY_KEEP"
                chmod 600 "$TPM_KEY_KEEP"
                CSR_CREATED=1
                USED_TPM=1
                KEY_STATUS="Private key generated inside the TPM and is non-exportable. A wrapped key handle (usable only with this TPM) was saved at:\\n${{TPM_KEY_KEEP}}"
            fi
        fi
    fi
fi

# ---- Attempt 2: software-protected key, imported into Secret Service ------
if [ "$CSR_CREATED" -ne 1 ]; then
    KEY_TMP="$WORKDIR/client-${{SUFFIX}}.key"
    ( umask 077; : > "$KEY_TMP" )
    rm -f "$CSR_PATH"

    if openssl req -new -newkey rsa:2048 -nodes \\
        -config "$CNF_PATH" \\
        -keyout "$KEY_TMP" \\
        -out "$CSR_PATH" \\
        >"$STDOUT_FILE" 2>"$STDERR_FILE" && [ -f "$CSR_PATH" ]; then

        chmod 644 "$CSR_PATH"

        KEY_IMPORT_OK=1
        if command -v secret-tool >/dev/null 2>&1; then
            secret-tool store --label="MPWT client key {suffix}" \\
                service mpwt-enrollment account "{suffix}" \\
                < "$KEY_TMP" >/dev/null 2>"$WORKDIR/import.err" || KEY_IMPORT_OK=0
        else
            KEY_IMPORT_OK=0
            echo "secret-tool not found" > "$WORKDIR/import.err"
        fi

        if command -v shred >/dev/null 2>&1; then
            shred -u -z "$KEY_TMP" 2>/dev/null || rm -f "$KEY_TMP"
        else
            rm -f "$KEY_TMP"
        fi

        if [ "$KEY_IMPORT_OK" -eq 1 ]; then
            CSR_CREATED=1
            KEY_STATUS="No TPM available -- private key was software-generated, imported into your Secret Service keyring (GNOME Keyring / KWallet), and the plaintext copy was shredded. This is software protection, not hardware-backed."
        else
            # Do NOT fall back to writing a bare .key file to disk.
            IMPORT_ERR=$(tail -3 "$WORKDIR/import.err" 2>/dev/null)
            rm -f "$CSR_PATH"
            ui_alert "CSR generation FAILED: could not protect the private key.\\n\\nNeither a TPM nor a working Secret Service keyring (secret-tool) was available (${{IMPORT_ERR}}), and this script will not save an unprotected private key to disk.\\n\\nInstall 'tpm2-tss-engine tpm2-tools' for hardware-backed keys, or 'gnome-keyring'/'libsecret-tools' for keyring protection, then try again. Contact IT admin if you need help."
            exit 1
        fi
    else
        ERR_MSG=$(tail -20 "$STDOUT_FILE" "$STDERR_FILE" 2>/dev/null)
        if command -v shred >/dev/null 2>&1; then
            shred -u -z "$KEY_TMP" 2>/dev/null || rm -f "$KEY_TMP"
        else
            rm -f "$KEY_TMP"
        fi
        ui_alert "CSR generation FAILED.\\n${{ERR_MSG}}\\nContact IT admin."
        exit 1
    fi
fi

ui_alert "CSR created:\\n${{CSR_PATH}}\\n\\n${{KEY_STATUS}}\\n\\nDone. Please send '${{CSR_NAME}}' back to your Admin.\\n\\nYou can close this terminal window now."
exit 0
'''

# ── Run commands ──────────────────────────────────────────────────────────────
# All three OSes are now self-running scripts (Windows .ps1, macOS/Linux .sh),
# so there is no separate copy-paste command left to hand to the user. This
# function is kept only so the existing API route calling it doesn't need to
# change -- it always returns "" now. Safe to remove once that route is
# updated to stop calling it / stop sending "run_command" in the response.
def get_run_command(
    os_type:      str,
    employee_id:  str,
    device_order: int,
    cn:           str,
) -> str:
    return ""

# ── HMAC verification (unchanged) ─────────────────────────────────────────────

def verify_csr_hmac(
    csr_pem:     str,
    token:       str,
    employee_id: str,
    cn:          str,
    os_type:     str,
) -> bool:
    try:
        extracted = _extract_hmac_from_subject(csr_pem)
    except Exception as exc:
        logger.warning("HMAC subject extraction failed: %s", exc)
        return False

    if not extracted:
        logger.warning(
            "MPWT-TOKEN OU not found in CSR Subject  "
            "token=%.8s employee=%s -- CSR not from server config",
            token, employee_id,
        )
        return False

    expected = _make_hmac(token, employee_id, cn, os_type)
    valid = hmac.compare_digest(extracted.lower(), expected.lower())

    if valid:
        logger.info("HMAC OK  token=%.8s employee=%s", token, employee_id)
    else:
        logger.warning(
            "HMAC mismatch  token=%.8s employee=%s  "
            "extracted=%.8s expected=%.8s",
            token, employee_id, extracted, expected,
        )
    return valid


def _extract_hmac_from_subject(csr_pem: str) -> str:
    with tempfile.NamedTemporaryFile(
        suffix=".csr", mode="w", delete=False, encoding="utf-8"
    ) as tmp:
        tmp.write(csr_pem)
        tmp_path = tmp.name

    try:
        result = subprocess.run(
            ["openssl", "req", "-noout", "-subject", "-in", tmp_path],
            capture_output=True, text=True, timeout=10,
        )

        if result.returncode != 0:
            result = subprocess.run(
                ["openssl", "req", "-noout", "-subject",
                 "-inform", "DER", "-in", tmp_path],
                capture_output=True, text=True, timeout=10,
            )

        if result.returncode != 0:
            logger.warning(
                "openssl req -subject failed rc=%d: %s",
                result.returncode, result.stderr.strip()[:300],
            )
            return ""

        subject_line = result.stdout.strip()
        logger.debug("CSR subject: %s", subject_line)

        m = re.search(
            r"OU\s*=\s*(" + re.escape(_HMAC_OU_PREFIX) + r"[0-9A-Fa-f]{" + str(_HMAC_HEX_LEN) + r"})",
            subject_line,
            re.IGNORECASE,
        )
        if m:
            full_ou   = m.group(1)
            hmac_part = full_ou[len(_HMAC_OU_PREFIX):]
            logger.debug("HMAC OU extracted: %s", full_ou)
            return hmac_part

        logger.warning(
            "MPWT-TOKEN OU not found in subject: %s", subject_line
        )
        return ""

    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
